repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        stages: [pre-commit, pre-push]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=120]
        stages: [pre-commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]  # example

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # check https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        stages: [pre-commit, pre-push]
